// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbWQViDCUMA1cVUVn42pu3tNOw83XgUFM',
    appId: '1:47114877694:web:ad19c641e94f3eeed283af',
    messagingSenderId: '47114877694',
    projectId: 'edunetdemo-5c098',
    authDomain: 'edunetdemo-5c098.firebaseapp.com',
    storageBucket: 'edunetdemo-5c098.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACdw03Mh0b7fabnCNZb5PBbpmxuORmOHg',
    appId: '1:47114877694:android:f4bab8d0f59173cfd283af',
    messagingSenderId: '47114877694',
    projectId: 'edunetdemo-5c098',
    storageBucket: 'edunetdemo-5c098.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLb8FOnHJ_O7AhgQyNw8M9NEFvMwoC7SE',
    appId: '1:47114877694:ios:fdfd0d091a5ab717d283af',
    messagingSenderId: '47114877694',
    projectId: 'edunetdemo-5c098',
    storageBucket: 'edunetdemo-5c098.appspot.com',
    iosBundleId: 'com.example.edunetdemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLb8FOnHJ_O7AhgQyNw8M9NEFvMwoC7SE',
    appId: '1:47114877694:ios:daa6305bf76c37aad283af',
    messagingSenderId: '47114877694',
    projectId: 'edunetdemo-5c098',
    storageBucket: 'edunetdemo-5c098.appspot.com',
    iosBundleId: 'com.example.edunetdemo.RunnerTests',
  );
}
